### Note: To keep the suggested file and directory structure run "snakemake dir_setup"
### This will generate a subfolder structure as presented here within your directory. 
### It will only work if an 'out' and a 'log' folder already exist

## general settings
ROOT: "."
R_lib: "packrat/lib/"
src: "src/"
log: "logs/"
out: "out/"

## Path to scripts
src_data: "src/data/"
src_meta: "src/meta_files/"
src_meta_sim: "src/meta_files/sim/"
src_data_mgt: "src/data_management/"
src_analysis: "src/analysis/"
src_summary: "src/summary/"
src_characterization: "src/characterization/"
src_sim: "src/simulation/"

## Path to output 
out_set: "out/settings/"
out_norm: "out/normalization/"
out_vp: "out/variance_part/"
out_abund: "out/abundance/"
out_cms: "out/cms/"
out_de: "out/de/"
out_type: "out/type/"
out_summary: "out/summary/"
out_edger: "out/edger/"
out_sim: "out/sim/"
out_sim_char: "out/sim_char/"
out_adjust_params: "out/adjust_params/"
out_sim_vp: "out/sim_variance_part/"
out_sim_abund: "out/sim_abundance/"
out_sim_de: "out/sim_de/"
out_sim_type: "out/sim_type/"
out_sim_summary: "out/sim_summary/"
out_sim_sumcms: "out/sim_sumcms/"



## Path to logs
log_dir: "log/dir_setup/"
log_sim_vars: "log/sim_vars/"
log_set: "log/settings/"
log_norm: "log/normalization/"
log_vp: "log/variance_part/"
log_abund: "log/abundance/"
log_cms: "log/cms/"
log_de: "log/de/"
log_type: "log/type/"
log_summary: "log/summary/"
log_edger: "log/edger/"
log_sim: "log/sim/"
log_sim_char: "log/sim_char/"
log_adjust_params: "log/adjust_params/"
log_sim_vp: "log/sim_variance_part/"
log_sim_abund: "log/sim_abundance/"
log_sim_de: "log/sim_de/"
log_sim_type: "log/sim_type/"
log_sim_sumcms: "log/sim_sumcms/"
log_sim_QC: "log/sim_QC/"

## Path to website files
docs: "docs/"
docs_libs: "docs/site_libs"


## Subdirectory names 
### Names of subfdirectories to be generated in output and log directories
### Here they correspond to the rule names
dir_names: settings,normalization,abundance,variance_part,cms,de,type,summary,edger,sim,sim_vars,sim_char,adjust_params,sim_variance_part,sim_abundance,sim_de,sim_type,sim_summary,sim_sumcms,sim_QC


